services:
  postgres:
    container_name: postgres
    image: postgres:18.6
    environment:
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_USER=user
      - POSTGRES_DB=order_db
    ports:
      - 6000:5432
    volumes:
      - postgres:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis:8.8
    ports:
      - 6001:6379

volumes:
  postgres:
